name: agu-data-viz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12

  - matplotlib=3.7.1
  - seaborn=0.13.1
  - plotnine=0.12.4

  - bokeh=3.3.4
  - panel=1.3.8

  - pandas=2.0.3
  - numpy=1.25.2
  - xarray=2023.7.0

  - jupyterlab=4.0.2

  - pip
  - pip:
    - flexitext==0.2.0
