name: agu-data-viz-02
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12

  - matplotlib=3.7.1
  - seaborn=0.12.2
  - plotnine=0.10.1
  - mizani=0.9.2

  - bokeh=2.4.3
  - ipyvizzu=0.15.0
  - panel=0.14.4

  - pandas=1.5.3
  - numpy=1.22.4
  - xarray=2022.12.0

  - jupyterlab=4.0.2
